name: Sync to GitLab

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab https://${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_REPO#https:// }}
          git push --force --mirror gitlab
