name: Sync to GitLab

on:
  push:
    branches:
      - main
  delete: {} # also sync branch/tag deletions

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # full history so mirror works

      - name: Push to GitLab (mirror all branches & tags)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ secrets.GITLAB_REPO }}
          git push --force --mirror gitlab
